# Site settings
name: "rubenhm.org"
title: "Rubén Hernández-Murillo"
description: "My Research Website by Ruben Hernandez-Murillo"
author: "Rubén Hernández-Murillo"
baseurl: ""
url: "http://rubenhm.org"
exclude: ["CNAME", "Rakefile", "MIT-LICENSE", "README.md"]

# Build settings
markdown: redcarpet
permalink: pretty

# Jekyll-scholar
scholar:
  style:  assets/bibliography/chicago-author-date.csl
  locale: en

  sort_by: year
  order: descending

  source: assets/bibliography
  bibliography: "bibliography.bib"
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


