# Site settings
name: "rubenhm.org"
title: "Rubén Hernández-Murillo"
description: "Research, Writings + Code"
author: "Rubén Hernández-Murillo"
baseurl: ""
url: "http://rubenhm.org"
exclude: ["Makefile","mkpdf.sh","Rakefile", "MIT-LICENSE", "build-cv"]


# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
permalink: pretty

# Jekyll-scholar
scholar:
  style:  assets/bibliography/chicago-author-date.csl
  locale: en

  sort_by: year
  order: descending

  source: assets/bibliography
  bibliography: "bibliography.bib"
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


# Sitemap builder
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/news.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/news/index.xml"
    include_posts:
        - "/index.html"
        - "/news/index.html"
        - "/blog/index.html"
    change_frequency_name: "weekly"
    # priority_name: "priority"