# 
# Common variables

# Location of BIB and CSL files
BIBFILE= /home/ruben/repos/website/rubenhm.org/assets/bibliography/bibliography.bib
CSLFILE= /home/ruben/repos/website/rubenhm.org/assets/bibliography/review.csl
