# 
# Common variables

# Location of BIB and CSL files
WORKDIR=/home/ruben/repos/personal/rubenhm.github.io
BIBFILE=$(WORKDIR)/assets/bibliography/bibliography.bib
CSLFILE=$(WORKDIR)/assets/bibliography/review.csl